import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { authTables } from "@convex-dev/auth/server";

/**
 * Vellum data model.
 *
 * Everything is a page — documents, databases, and database rows alike
 * (exactly like Notion). A page whose `type` is "database" carries a
 * property schema (`dbProps`) and its children are its rows. Rows carry
 * `props` (property values keyed by property id) and can still have full
 * rich-text `content`, so every row opens as a real page.
 */

export const propType = v.union(
  v.literal("text"),
  v.literal("number"),
  v.literal("select"),
  v.literal("multiSelect"),
  v.literal("date"),
  v.literal("checkbox"),
  v.literal("url"),
  v.literal("relation"),
  // Computed, never stored: read off the row's own timestamps.
  v.literal("createdTime"),
  v.literal("lastEditedTime"),
  // Computed: aggregates a property of related rows through a relation.
  v.literal("rollup"),
  // Computed: an expression over this row's other properties.
  v.literal("formula"),
  // Generated by the model from the row's own content, then *stored* like
  // any other value (unlike the computed types above) — generation costs a
  // network round-trip, so it must not re-run on every render.
  v.literal("ai"),
);

export const dbProp = v.object({
  id: v.string(),
  name: v.string(),
  type: propType,
  width: v.optional(v.number()),
  options: v.optional(
    v.array(
      v.object({
        id: v.string(),
        name: v.string(),
        color: v.string(),
      }),
    ),
  ),
  // Relation properties: the database page whose rows this prop links to.
  // Deliberately v.string(), not v.id("pages") — offline clients hold temp
  // ids until their create replays, and dbProps ride through createWithDoc.
  targetId: v.optional(v.string()),
  // Rollup properties. All three hold client-generated prop ids (or the
  // "__title" sentinel), never page ids — nothing here needs id remapping.
  relationPropId: v.optional(v.string()), // which relation column to follow
  rollupPropId: v.optional(v.string()), // which property of the target rows
  rollupCalc: v.optional(v.string()), // count | sum | avg | min | max | …
  // Formula properties: the expression source (see src/lib/formula.ts).
  // Evaluated client-side at render; never stored as a value.
  formula: v.optional(v.string()),
  // AI properties (see convex/ai.ts `fillProperty`). `aiPrompt` carries the
  // instruction when `aiKind` is "custom".
  aiKind: v.optional(v.string()),
  aiPrompt: v.optional(v.string()),
});

export const activeView = v.union(
  v.literal("table"),
  v.literal("board"),
  v.literal("calendar"),
  v.literal("gallery"),
  v.literal("timeline"),
);

const filterLogic = v.union(v.literal("and"), v.literal("or"));
// `op` and `value` are interpreted client-side (src/lib/dbviews.ts); the
// value never holds page ids — relation filters are presence-only, which is
// what keeps offline temp ids out of saved views.
const filterCondition = v.object({
  propId: v.string(),
  op: v.string(),
  value: v.optional(v.any()),
});
// Validators can't recurse, so nesting is one explicit level deep — the
// same cap the filter-builder UI enforces.
const filterGroup = v.object({
  logic: filterLogic,
  conditions: v.array(
    v.union(
      filterCondition,
      v.object({ logic: filterLogic, conditions: v.array(filterCondition) }),
    ),
  ),
});

/** One saved database view: layout plus its filter/sort/group config. */
export const dbView = v.object({
  id: v.string(),
  name: v.string(),
  kind: activeView,
  filter: v.optional(filterGroup),
  sorts: v.optional(
    v.array(
      v.object({
        key: v.string(),
        dir: v.union(v.literal("asc"), v.literal("desc")),
      }),
    ),
  ),
  groupBy: v.optional(v.string()),
  boardGroupBy: v.optional(v.string()),
  calendarBy: v.optional(v.string()),
});

export default defineSchema({
  // Convex Auth's account/session/user tables. Multi-tenant since Phase 1
  // (docs/multi-user-plan.md): every workspace row carries an `ownerId` and
  // functions scope to the signed-in user (see lib/auth.ts).
  ...authTables,

  // authTables.users, replicated field-for-field plus `inviteCode`: the
  // Password provider's profile() return is written verbatim to this table,
  // and it's how the sign-up form's invite code reaches the transactional
  // check in auth.ts `afterUserCreatedOrUpdated` (which clears it again).
  users: defineTable({
    name: v.optional(v.string()),
    image: v.optional(v.string()),
    email: v.optional(v.string()),
    emailVerificationTime: v.optional(v.number()),
    phone: v.optional(v.string()),
    phoneVerificationTime: v.optional(v.number()),
    isAnonymous: v.optional(v.boolean()),
    inviteCode: v.optional(v.string()),
  })
    .index("email", ["email"])
    .index("phone", ["phone"]),

  /**
   * Sign-up invite codes, minted by the owner (convex/admin.ts). A code is
   * single-use: redemption happens inside the same transaction that creates
   * the user, so a race on one code creates exactly one account. Redeemed
   * codes are kept as an audit trail.
   */
  invites: defineTable({
    code: v.string(),
    note: v.optional(v.string()), // who it's for, freeform
    createdAt: v.number(),
    redeemedBy: v.optional(v.id("users")),
    redeemedAt: v.optional(v.number()),
  })
    .index("by_code", ["code"])
    // Throwaway: exists only to prove the Vercel deploy key can create
    // indexes (deployment:data:view). Removed in the next commit.
    .index("by_createdAt_keytest", ["createdAt"]),

  /**
   * Uploaded files, attributed to their uploader for the 50 MB quota
   * (docs/multi-user-plan.md). Known v1 limitation: rows are never removed
   * when pages are deleted (content may share URLs across duplicates), so
   * quota counts lifetime uploads, not live usage.
   */
  files: defineTable({
    storageId: v.id("_storage"),
    ownerId: v.id("users"),
    size: v.number(),
    createdAt: v.number(),
  })
    .index("by_owner", ["ownerId"])
    .index("by_storageId", ["storageId"]),

  /**
   * AI spend accounting, one row per (user, calendar month), cost in
   * micro-USD from OpenRouter's per-call accounting. The owner is exempt
   * and never recorded, so the by_month sum IS the shared non-owner pool.
   */
  aiUsage: defineTable({
    userId: v.id("users"),
    month: v.string(), // "2026-08" (UTC)
    costMicroUsd: v.number(),
    calls: v.number(),
  })
    .index("by_user_month", ["userId", "month"])
    .index("by_month", ["month"]),

  pages: defineTable({
    // Optional only for the widen→backfill→narrow migration; after the
    // backfill every row has it and all code treats it as required.
    ownerId: v.optional(v.id("users")),
    title: v.string(),
    type: v.union(v.literal("doc"), v.literal("database")),
    parentId: v.optional(v.id("pages")),
    rank: v.number(),
    icon: v.optional(v.string()),
    cover: v.optional(v.string()), // css gradient token ("gradient:N") or a URL
    content: v.optional(v.any()), // BlockNote Block[]
    contentText: v.optional(v.string()), // plain-text extraction of content
    searchText: v.optional(v.string()), // title + contentText (search index field)
    props: v.optional(v.record(v.string(), v.any())), // row property values
    isFavorite: v.optional(v.boolean()),
    // Marks a page as a reusable template — excluded from the page tree and
    // listed in the sidebar's Templates section instead.
    isTemplate: v.optional(v.boolean()),
    font: v.optional(
      v.union(v.literal("default"), v.literal("serif"), v.literal("mono")),
    ),
    smallText: v.optional(v.boolean()),
    fullWidth: v.optional(v.boolean()),
    locked: v.optional(v.boolean()),
    // End-to-end encrypted Vault. True on the vault root and every
    // descendant (denormalized so guards never walk the parent chain).
    // Vault pages carry client-encrypted `title`/`content` and empty
    // search fields — the server never sees their plaintext.
    vault: v.optional(v.boolean()),
    inTrash: v.optional(v.boolean()),
    trashRoot: v.optional(v.boolean()), // true only on the page the user trashed
    trashedAt: v.optional(v.number()),
    dbProps: v.optional(v.array(dbProp)),
    // Saved views. Once set, activeView/boardGroupBy/calendarBy become a
    // read-only fallback used to derive the initial set (see lib/dbviews.ts).
    views: v.optional(v.array(dbView)),
    activeView: v.optional(activeView),
    boardGroupBy: v.optional(v.string()),
    calendarBy: v.optional(v.string()),
    updatedAt: v.number(),
    // Bumped only by content/title edits — the LWW conflict timestamp for
    // offline sync (a favorite-toggle must not beat a real edit).
    contentUpdatedAt: v.optional(v.number()),
    // Client-generated id of pages created offline; makes replayed
    // createWithDoc calls idempotent across crash/retry.
    clientKey: v.optional(v.string()),
    // "Publish to web": an unguessable slug serving this page publicly at
    // /p/<slug>. Absent means private — the slug IS the access control, so
    // unpublishing must clear it rather than flag it.
    publicSlug: v.optional(v.string()),
    publishedAt: v.optional(v.number()),
  })
    .index("by_parent", ["parentId"])
    .index("by_owner", ["ownerId"])
    .index("by_clientKey", ["clientKey"])
    .index("by_publicSlug", ["publicSlug"])
    .searchIndex("search", {
      searchField: "searchText",
      filterFields: ["ownerId"],
    }),

  /**
   * Point-in-time snapshots of a page's content, captured server-side by
   * `updateContent` at most once per SNAPSHOT_INTERVAL_MS. Deliberately a
   * separate table: the offline replica mirrors `pages` only, so history
   * never touches the sync index, reconcile, or the outbox.
   */
  pageVersions: defineTable({
    ownerId: v.optional(v.id("users")), // optional pending backfill
    pageId: v.id("pages"),
    title: v.string(),
    content: v.optional(v.any()),
    savedAt: v.number(),
  })
    .index("by_page", ["pageId", "savedAt"])
    .index("by_owner", ["ownerId"]),

  /**
   * Page comments. Like pageVersions, a separate table the offline replica
   * never mirrors — so commenting touches neither `syncIndex`, reconcile,
   * nor the outbox, and is simply unavailable while offline.
   */
  comments: defineTable({
    ownerId: v.optional(v.id("users")), // optional pending backfill
    pageId: v.id("pages"),
    text: v.string(),
    createdAt: v.number(),
    resolved: v.optional(v.boolean()),
  })
    .index("by_page", ["pageId", "createdAt"])
    .index("by_owner", ["ownerId"]),
});
