import { useEffect, useRef, useState } from "react";
import { FileText, Loader2, Sparkles } from "lucide-react";
import { AiAnswer, PageId } from "../lib/types";
import { useAi } from "../data";

/**
 * Notion's "ask your workspace": a question answered from the user's own
 * pages, with the pages it drew on listed as clickable citations.
 *
 * Retrieval happens server-side over the existing search index
 * (convex/ai.ts `ask`); this component only asks and renders. The Vault is
 * excluded there, not here — its content is ciphertext the server cannot
 * read even if it wanted to.
 */
export default function AskAiModal({
  onClose,
  onOpenPage,
}: {
  onClose: () => void;
  onOpenPage: (id: PageId) => void;
}) {
  const ai = useAi();
  const [question, setQuestion] = useState("");
  const [busy, setBusy] = useState(false);
  const [answer, setAnswer] = useState<AiAnswer | null>(null);
  const [error, setError] = useState<string | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  const submit = async () => {
    const q = question.trim();
    if (!q || busy) return;
    setBusy(true);
    setError(null);
    setAnswer(null);
    try {
      setAnswer(await ai.ask(q));
    } catch (err) {
      const data = (err as { data?: unknown }).data;
      setError(
        typeof data === "string"
          ? data
          : err instanceof Error
            ? err.message
            : "Something went wrong.",
      );
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="ask-ai-backdrop" onMouseDown={onClose}>
      <div className="ask-ai" onMouseDown={(e) => e.stopPropagation()}>
        <div className="ask-ai-input">
          {busy ? (
            <Loader2 size={18} className="ai-spin" />
          ) : (
            <Sparkles size={18} className="ai-menu-spark" />
          )}
          <input
            ref={inputRef}
            value={question}
            placeholder="Ask anything about your workspace…"
            disabled={busy}
            onChange={(e) => setQuestion(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                e.preventDefault();
                void submit();
              }
            }}
          />
        </div>

        {error && <div className="ai-menu-error">{error}</div>}

        {!answer && !error && (
          <div className="ask-ai-empty">
            {busy
              ? "Reading your pages…"
              : "Answers are drawn only from your own pages, with citations. The Vault is never included."}
          </div>
        )}

        {answer && (
          <>
            <div className="ask-ai-body">{answer.answer}</div>
            {answer.sources.length > 0 && (
              <div className="ask-ai-sources">
                <div className="ask-ai-sources-label">Sources</div>
                {answer.sources.map((s, i) => (
                  <button
                    key={s.pageId}
                    className="ask-ai-source"
                    onClick={() => {
                      onOpenPage(s.pageId);
                      onClose();
                    }}
                  >
                    <span className="ask-ai-source-num">[{i + 1}]</span>
                    {s.icon ? (
                      <span>{s.icon}</span>
                    ) : (
                      <FileText size={14} />
                    )}
                    {s.title}
                  </button>
                ))}
              </div>
            )}
            <div className="ask-ai-footer">
              Generated by {answer.model} — verify anything that matters.
            </div>
          </>
        )}
      </div>
    </div>
  );
}
